export const SYMBOLS = Object.freeze({
  // KEYS
  USER: 'USER',
  STATE: 'STATE',
  ENVIRONMENT: 'ENVIRONMENT',
  ENDPOINTS: 'ENDPOINTS',
  LANG_DEFAULT: 'LANG.DEFAULT',
  LANG_SUPPORTED: 'LANG.SUPPORTED',
  STATE_NAVBAR: 'STATE.NAVBAR',
  STATE_FOOTER: 'STATE.FOOTER',
  UI_STATE_NAVBAR: 'UI.NAVBAR',
  UI_STATE_FOOTER: 'UI.FOOTER',
  API_VERSION: 'API_VERSION',
  API_DOMAIN: 'API_DOMAIN',
  /* tslint:disable */
  EMAILREGEX: '[a-z0-9!#$%&\'*+\/=?^_`{|}~.-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*',
  /* tslint:enable */
  DOMAINS_AUTH: 'DOMAINS.AUTH',
  DOMAINS_BUYER: 'DOMAINS.BUYER',
  DOMAINS_MANUFACTURER: 'DOMAINS.MANUFACTURER',
  DOMAINS_LOCAL: 'DOMAINS.LOCAL',
  DOMAINS_SITE: 'DOMAINS.SITE',
  DOMAINS_UPLOADER: 'DOMAINS.UPLOADER',
  DOMAINS_LOGGING: 'DOMAINS.LOGGING',
  ENDPOINTS_COMMON_NAV: 'ENDPOINTS.COMMON_NAV',
  ENDPOINTS_COMMON_FOOT: 'ENDPOINTS.COMMON_FOOT',
  ENDPOINTS_AUTH_LOGIN: 'ENDPOINTS.AUTH_LOGIN',
});
